on: [push] #foo
jobs:
  make-ipxe:
    name: make ipxe
    runs-on: ubuntu-24.04
    steps:
      - name: checkout self/this
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: self
      - name: checkout ipxe/ipxe github repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          #ref: v1.20.1 #try to go with latest
          repository: ipxe/ipxe
          path: ipxe
      - name: install ipxe build deps
        run: |
          sudo apt install -y build-essential isolinux mtools xorriso
      - name: build ipxe
        run: |
          self_root="${GITHUB_WORKSPACE}/self"
          ipxe_root="${GITHUB_WORKSPACE}/ipxe"
          cp ${self_root}/ipxe_config/config.ipxe ${ipxe_root}/src/
          cp ${self_root}/ipxe_config/general.h ${ipxe_root}/src/config/
          cp ${self_root}/ipxe_config/console.h ${ipxe_root}/src/config/
          cd ${ipxe_root}/src/
          #make bin-x86_64-efi/ipxe.efi EMBED=config.ipxe -j2
          make bin-x86_64-efi/snponly.efi EMBED=config.ipxe -j2
          make bin-x86_64-efi/ipxe.iso EMBED=config.ipxe -j2
      - name: upload ipxe.efi as artifact
        uses: actions/upload-artifact@v4
        with:
          name: snponly.efi
          path: |
            ${{ github.workspace }}/ipxe/src/bin-x86_64-efi/snponly.efi
      - name: upload ipxe.efi as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ipxe.iso
          path: |
            ${{ github.workspace }}/ipxe/src/bin-x86_64-efi/ipxe.iso

